import type { NextPage } from 'next'
import Head from 'next/head'
import Script from 'next/script'
import styles from '../styles/Home.module.css'
import { Timeline } from '../components/Timeline'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Timeline>
          <Timeline.Item>
            <h1>1231</h1>
          </Timeline.Item>
          <Timeline.Item>
            <h1>1231</h1>
            <h1>1231</h1>
          </Timeline.Item>
        </Timeline>
      </main>
      <Script src={'//hm.baidu.com/hm.js'} />
    </div>
  )
}

export default Home
