import type { NextPage } from 'next'
import Head from 'next/head'
import Script from 'next/script'

const Home: NextPage = () => {
  return (
    <div className={''}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={''}>
        <h1 className={'flex bg-red-300 font-red'}>Hello World</h1>
      </main>
      <Script src={'//hm.baidu.com/hm.js'} />
    </div>
  )
}

export default Home
